name: Build ğŸ‘·â€â™€ï¸ and Test ğŸ“
on: push

jobs:
  build-and-cache:
    name: âš™ï¸ Build and ğŸ’¸ Cache
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: âš™ï¸ Build
        run: yarn build

      - name: ğŸ“š Build Storybook
        run: yarn build-storybook

      - name: ğŸ’¸ Cache Build
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    name: ğŸ‘€ ESLint
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Load Cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸ§¶ Lint
        run: yarn lint

  unit-test:
    name: ğŸ  Unit Test
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Load Cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸƒâ€â™€ï¸ Run Unit Tests
        run: yarn test

  ui-visual-regression:
    name: ğŸ–¼ Visual Regression Test
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    if: false
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Load Storybook Cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸƒâ€â™€ï¸ Run Visual Regression Tests
        run: yarn test:visual-regression-ci

      - name: Archive Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-visual-regression-artifacts
          path: ui-tests/snapshots/

  ui-accessibility:
    name: Accessibility Checks
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Load Storybook Cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Run Accessibility Checks
        run: yarn test:a11y-ci
