name: Build ğŸ‘·â€â™€ï¸ and Test ğŸ“
on: push

jobs:
  build-and-cache:
    name: âš™ï¸ Build and ğŸ’¸ Cache
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: âš™ï¸ Build
        run: yarn build

      - name: ğŸ“¦ Export
        run: yarn export

      - name: ğŸ’¸ Cache Build
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Cache Cypress
        uses: actions/cache@v2
        id: restore-cypress
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ github.sha }}

  lint:
    name: ğŸ‘€ ESLint
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸ§¶ Lint
        run: yarn lint

  unit-test:
    name: ğŸ  Unit Test (Components)
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸƒâ€â™€ï¸ Run Unit Tests
        run: yarn test:components

  functional-test:
    name: ğŸ³ Functional Test (Features)
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Build Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Load Cypress Cache
        uses: actions/cache@v2
        id: restore-cypress
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ github.sha }}

      - name: ğŸƒâ€â™€ï¸ Run Functional Tests
        run: yarn test:features-ci
        env:
          TEST_SERVER_PORT: 3000

  ui-visual-regression:
    name: ğŸ–¼ Visual Regression Test
    runs-on: macos-11
    needs: [build-and-cache]
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Build Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Install Deps
        run: yarn install

      - name: ğŸƒâ€â™€ï¸ Run Visual Regression Tests
        run: yarn test:visual-regression-ci

      - name: Archive Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ui-visual-regression-artifacts
          path: ui-tests/snapshots/

  ui-accessibility:
    name: Accessibility Checks
    runs-on: ubuntu-latest
    needs: [build-and-cache]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Build Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Run Accessibility Checks
        run: yarn test:a11y-ci

  deploy:
    name: ğŸš€ Deploy
    needs:
      [lint, unit-test, functional-test, ui-visual-regression, ui-accessibility]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Load Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: ğŸ›‘ Disable Jekyll Processing
        run: touch out/.nojekyll

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: release
          folder: out
