name: Build ğŸ‘·â€â™€ï¸ and Test ğŸ“
on: push

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: ğŸ§¶ Lint
        run: yarn lint

  unit-test:
    name: ğŸ  Unit Test (Components)
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: ğŸƒâ€â™€ï¸ Run Unit Tests
        run: yarn test:components

  functional-test:
    name: ğŸ³ Functional Test (Features)
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: ğŸ‘¯â€â™€ï¸ Copy Test Environment Variables
        run: cp .env.example .env

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: ğŸƒâ€â™€ï¸ Run Functional Tests
        run: yarn test:features-ci

  verify-deployment:
    name: âœ… Verify Deployment ğŸš€
    needs: [lint, unit-test, functional-test]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: ğŸ’¸ Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn-lock.json') }}

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: âš™ï¸ Build
        run: yarn build

      - name: ğŸ“¦ Export
        run: yarn export

  deploy:
    name: ğŸš€ Deploy
    needs: [lint, unit-test, functional-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v2

      - name: ğŸ’¸ Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn-lock.json') }}

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ“¥ Install Dependencies
        run: yarn install

      - name: âš™ï¸ Build
        run: yarn build

      - name: ğŸ“¦ Export
        run: yarn export

      - name: ğŸ›‘ Disable Jekyll Processing
        run: touch out/.nojekyll

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: release
          FOLDER: out
          CLEAN: true
